name: Publish catii on PYPI

on:
  release:
    types: [created]

jobs:
  build_wheels:
    name: Build wheels on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install cibuildwheel
        run: pip install cibuildwheel
      - name: Build wheels with cibuildwheel
        run: cibuildwheel --output-dir dist

  pypi:
    needs: build_wheels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install twine
        run: pip install twine
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist
      - name: Publish on PYPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_APIKEY }}
        run: twine upload dist/*
